"""inicial

Revision ID: 13da00781456
Revises: 
Create Date: 2026-03-29 10:05:47.969711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13da00781456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_aplicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo_valor', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracion_aplicacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracion_aplicacion_clave'), ['clave'], unique=True)

    op.create_table('configuracion_horas_nocturnas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ambito', sa.String(length=32), nullable=False),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('festivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_festivos_fecha'), ['fecha'], unique=False)

    op.create_table('plantillas_planificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo_electronico', sa.String(length=255), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=64), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intentos_fallidos_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=128), nullable=True),
    sa.Column('expira_token_recuperacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo_electronico'), ['correo_electronico'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_token_recuperacion'), ['token_recuperacion'], unique=False)

    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo_empleado', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('documento_identidad', sa.String(length=32), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('horas_semanales', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vacaciones_anuales', sa.Integer(), nullable=False),
    sa.Column('saldo_vacaciones', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=80), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('centro_trabajo', sa.String(length=200), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['empleados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empleados_codigo_empleado'), ['codigo_empleado'], unique=True)
        batch_op.create_index(batch_op.f('ix_empleados_documento_identidad'), ['documento_identidad'], unique=False)

    op.create_table('planificaciones_semanales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio_semana', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planificaciones_semanales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planificaciones_semanales_inicio_semana'), ['inicio_semana'], unique=False)

    op.create_table('registros_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_entidad', sa.String(length=80), nullable=False),
    sa.Column('id_entidad', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=64), nullable=False),
    sa.Column('usuario_actor_id', sa.Integer(), nullable=True),
    sa.Column('rol_actor', sa.String(length=64), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('estado_anterior_json', sa.Text(), nullable=True),
    sa.Column('estado_nuevo_json', sa.Text(), nullable=True),
    sa.Column('direccion_ip', sa.String(length=64), nullable=True),
    sa.Column('agente_usuario', sa.String(length=512), nullable=True),
    sa.Column('origen_cambio', sa.String(length=64), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_actor_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_auditoria_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_auditoria_id_entidad'), ['id_entidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_auditoria_tipo_entidad'), ['tipo_entidad'], unique=False)

    op.create_table('items_planificacion_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planificacion_semanal_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('nombre_plantilla', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planificacion_semanal_id'], ['planificaciones_semanales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_planificacion_semanal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_planificacion_semanal_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_planificacion_semanal_planificacion_semanal_id'), ['planificacion_semanal_id'], unique=False)

    op.create_table('items_plantilla_planificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('etiqueta_rol', sa.String(length=80), nullable=True),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_planificacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items_plantilla_planificacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_plantilla_planificacion_plantilla_id'), ['plantilla_id'], unique=False)

    op.create_table('registros_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_registro', sa.String(length=32), nullable=False),
    sa.Column('fecha_hora_servidor', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_cliente', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precision_metros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('texto_ubicacion', sa.String(length=500), nullable=True),
    sa.Column('direccion_ip', sa.String(length=64), nullable=True),
    sa.Column('agente_usuario', sa.String(length=512), nullable=True),
    sa.Column('origen', sa.String(length=32), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registros_jornada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_jornada_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_jornada_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_jornada_fecha_hora_servidor'), ['fecha_hora_servidor'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_jornada_tipo_registro'), ['tipo_registro'], unique=False)

    op.create_table('solicitudes_vacaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('numero_dias', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('solicitado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aprobado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_vacaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_vacaciones_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_vacaciones_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_vacaciones_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_vacaciones_fecha_inicio'), ['fecha_inicio'], unique=False)

    op.create_table('solicitudes_correccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empleado_id', sa.Integer(), nullable=False),
    sa.Column('registro_jornada_id', sa.Integer(), nullable=True),
    sa.Column('tipo_solicitud', sa.String(length=64), nullable=False),
    sa.Column('valor_solicitado', sa.Text(), nullable=True),
    sa.Column('valor_actual', sa.Text(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=32), nullable=False),
    sa.Column('revisado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('revisado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas_resolucion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registro_jornada_id'], ['registros_jornada.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revisado_por_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_correccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_correccion_empleado_id'), ['empleado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_correccion_estado'), ['estado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_correccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_correccion_estado'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_correccion_empleado_id'))

    op.drop_table('solicitudes_correccion')
    with op.batch_alter_table('solicitudes_vacaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_vacaciones_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_vacaciones_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_vacaciones_estado'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_vacaciones_empleado_id'))

    op.drop_table('solicitudes_vacaciones')
    with op.batch_alter_table('registros_jornada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_jornada_tipo_registro'))
        batch_op.drop_index(batch_op.f('ix_registros_jornada_fecha_hora_servidor'))
        batch_op.drop_index(batch_op.f('ix_registros_jornada_estado'))
        batch_op.drop_index(batch_op.f('ix_registros_jornada_empleado_id'))

    op.drop_table('registros_jornada')
    with op.batch_alter_table('items_plantilla_planificacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_plantilla_planificacion_plantilla_id'))

    op.drop_table('items_plantilla_planificacion')
    with op.batch_alter_table('items_planificacion_semanal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_planificacion_semanal_planificacion_semanal_id'))
        batch_op.drop_index(batch_op.f('ix_items_planificacion_semanal_empleado_id'))

    op.drop_table('items_planificacion_semanal')
    with op.batch_alter_table('registros_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_tipo_entidad'))
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_id_entidad'))
        batch_op.drop_index(batch_op.f('ix_registros_auditoria_creado_en'))

    op.drop_table('registros_auditoria')
    with op.batch_alter_table('planificaciones_semanales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planificaciones_semanales_inicio_semana'))

    op.drop_table('planificaciones_semanales')
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empleados_documento_identidad'))
        batch_op.drop_index(batch_op.f('ix_empleados_codigo_empleado'))

    op.drop_table('empleados')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_token_recuperacion'))
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_correo_electronico'))

    op.drop_table('usuarios')
    op.drop_table('plantillas_planificacion')
    with op.batch_alter_table('festivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_festivos_fecha'))

    op.drop_table('festivos')
    op.drop_table('configuracion_horas_nocturnas')
    with op.batch_alter_table('configuracion_aplicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracion_aplicacion_clave'))

    op.drop_table('configuracion_aplicacion')
    # ### end Alembic commands ###
